version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0
  azure-acr: circleci/azure-acr@0.1.4

jobs:
  lint:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test-requirements.txt
            flake8 --exclude venv

  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test-requirements.txt
            python -m pytest

  build_deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - setup_remote_docker
      - azure-acr/build-and-push-image:
          login-server-name: 28811containerregistry.azurecr.io
          registry-name: 28811containerregistry
          repo: flask-demo

workflows:
  version: 2
  lint_test_deploy:
    jobs:
      - lint
      - test
      - build_deploy:
          requires:
            - lint
            - test
